### ISSUE TITLE
Minor Changes

### ISSUE THREAD

**Issue by Git-Logan** [njitacm/jerseyctf-registration-site#4]
- **Under registration section:**  Small break from the registration form, then “Team sizes will range from 1 to 4 participants. Each participant should individually register, and on the day of the competition you will be able to gather your team on the JerseyCTF platform!”

- At the complete bottom of the website, add this URL: https://docs.google.com/document/d/1KvOADKuuKq0a603JKxUVTBYmR52cqs0zNyIbrAyTIdw/edit?usp=sharing as **Code of Conduct & Privacy Policy**

- Fix speakers uneven cards (?)

- Fix mobile version logo (?)

- Remove comments when done with everything

**Comment by SinghSanity** [comment]
Added the part to **Registration**, added **Code of Conduct & Privacy Policy** at the bottom, changed logo layout to make it more mobile friendly, removed all comments except calendar (which we will use a reference for later) and decided to keep speaker cards as is for now.
