### ISSUE TITLE
Sponsor and Speaker Updates

### ISSUE THREAD

**Issue by Git-Logan** [njitacm/jerseyctf-registration-site#5]
**Sponsor updates:**

Add SecurityInnovation to "Security Analyst" tier next to Contrast Security - https://www.securityinnovation.com/ 
![security_innovation](https://user-images.githubusercontent.com/65144990/109369049-0d00fd80-7869-11eb-9c63-ae4a3c517e31.png)

Add NJCCIC linked logo to "CISO" tier next to SpecterOps - https://www.cyber.nj.gov/
![NJCCIC](https://user-images.githubusercontent.com/65144990/109369093-2f931680-7869-11eb-9229-73e48399abb0.png)

Add NJCCIC linked logo next to SpecterOps under "Powered by" at the top

**Speaker updates:**
As the **first** card, add this speaker:

<img width="304" alt="MichaelGeraghty" src="https://user-images.githubusercontent.com/65144990/109369284-d5df1c00-7869-11eb-981b-dfb5316c27d3.png">

Michael Geraghty

CISO, State of New Jersey & Director, NJCCIC 

Don't include "Speaker Topic:", just write "Keynote Speaker"

https://www.linkedin.com/in/michael-geraghty-13139820/

**Comment by SinghSanity** [comment]
Added everything
